timeout: 3600s
steps:
- name: 'gcr.io/cloud-builders/wget'
  args: ["https://releases.hashicorp.com/terraform/${_TERRAFORM_VERSION}/terraform_${_TERRAFORM_VERSION}_linux_amd64.zip"]
- name: 'gcr.io/cloud-builders/docker'
  env:
  - 'TERRAFORM_VERSION=${_TERRAFORM_VERSION}'
  args:
  - build
  - --build-arg
  - TERRAFORM_VERSION=${_TERRAFORM_VERSION}
  - --tag
  - asia-east2-docker.pkg.dev/${PROJECT_ID}/polaris/terraform:${_TERRAFORM_VERSION}
  - --tag
  - asia-east2-docker.pkg.dev/${PROJECT_ID}/polaris/terraform:latest
  - .
  
- name: 'asia-east2.pkg.dev/${PROJECT_ID}/polaris/terraform:${_TERRAFORM_VERSION}'
  args: ['version']
  
- name: 'asia-east2-docker.pkg.dev/${PROJECT_ID}/polaris/terraform'
  args: ['init']
  dir: 'examples/workbench_simple_example'
  env:
    - "TF_VAR_project_id=${PROJECT_ID}"
    
images:
  - 'asia-east2-docker.pkg.dev/${PROJECT_ID}/polaris/terraform:${_TERRAFORM_VERSION}'
  - 'asia-east2-docker.pkg.dev/${PROJECT_ID}/polaris/terraform:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  
tags:
- 'ci'
- 'integration'

substitutions:
  _TERRAFORM_VERSION: 1.9.5
