timeout: 3600s
steps:
# - name: 'gcr.io/cloud-builders/wget'
#   args: ["https://releases.hashicorp.com/terraform/${_TERRAFORM_VERSION}/terraform_${_TERRAFORM_VERSION}_linux_amd64.zip"]
# - name: 'gcr.io/cloud-builders/docker'
#   env:
#   - 'TERRAFORM_VERSION=${_TERRAFORM_VERSION}'
#   args:
#   - build
#   - --build-arg
#   - TERRAFORM_VERSION=${_TERRAFORM_VERSION}
#   - --tag
#   - ${_TERRAFORM_IMAGE}:${_TERRAFORM_VERSION}
#   - --tag
#   - ${_TERRAFORM_IMAGE}:latest
#   - .
  
# - name: '${_TERRAFORM_IMAGE}:${_TERRAFORM_VERSION}'
#   args: ['version']
  
- name: 'asia-east2-docker.pkg.dev/${PROJECT_ID}/polaris/terraform'
  args: ['init']
  dir: 'examples/workbench_simple_example'
  env:
    - "TF_VAR_project_id=${PROJECT_ID}"

- name: 'asia-east2-docker.pkg.dev/${PROJECT_ID}/polaris/terraform'
  args: ['validate']
  dir: 'examples/workbench_simple_example'
  env:
    - "TF_VAR_project_id=${PROJECT_ID}"
    
- name: 'asia-east2-docker.pkg.dev/${PROJECT_ID}/polaris/terraform'
  args: ['plan','-out', 'tf.plan']
  dir: 'examples/workbench_simple_example'
  env:
    - "TF_VAR_project_id=${PROJECT_ID}"
    
- name: 'asia-east2-docker.pkg.dev/${PROJECT_ID}/polaris/terraform'
  args: ['show','-no-color', 'tf.plan > tfplan.txt']
  dir: 'examples/workbench_simple_example'
  env:
    - "TF_VAR_project_id=${PROJECT_ID}"    
# - name: 'asia-east2-docker.pkg.dev/${PROJECT_ID}/polaris/terraform'
#   args: ['apply']
#   dir: 'examples/workbench_simple_example'
#   env:
#     - "TF_VAR_project_id=${PROJECT_ID}"     
# images:
#   - '${_TERRAFORM_IMAGE}:${_TERRAFORM_VERSION}'
#   - '${_TERRAFORM_IMAGE}:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  
tags:
- 'ci'
- 'integration'

substitutions:
  _TERRAFORM_VERSION: 1.9.5
  _TERRAFORM_IMAGE: 'asia-east2-docker.pkg.dev/${PROJECT_ID}/polaris/terraform'
