timeout: 3600s
steps:
- name: 'asia-east2-docker.pkg.dev/${PROJECT_ID}/polaris/terraform'
  args: ['init']
  dir: 'examples/workbench_simple_example'
  env:
    - "project_id=${PROJECT_ID}"
- name: 'asia-east2-docker.pkg.dev/${PROJECT_ID}/polaris/terraform'
  args: ['validate']
  dir: 'examples/workbench_simple_example'
  env:
    - "project_id=${PROJECT_ID}"
- name: 'asia-east2-docker.pkg.dev/${PROJECT_ID}/polaris/terraform'
  args: ['plan']
  dir: 'examples/workbench_simple_example'
  env:
    - "project_id=${PROJECT_ID}"

options:
  logging: CLOUD_LOGGING_ONLY
  
tags:
- 'ci'
- 'integration'

substitutions:
  _TERRAFORM_VERSION: 1.9.5
